#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Places.Droid.Resource", IsApplication=true)]

namespace Places.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int appleBees = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int burgerKing = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int foleySportsComplex = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int gulfBowl = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int mcdonalds = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int menu = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int radioShack = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int subway = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int swattersSportsComplex = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int tacoBell = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int tanger = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int walmart = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
	}
}
#pragma warning restore 1591
